config/routes.rb
Rails.application.routes.draw do
 
  root to: 'home#index'
  
  get 'home/index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  
  resources :teachers
  resources :curriculums
  resources :schools
  resources :jobs
  resources :users
  
  
  

end

app/models/job.rb
class Job < ActiveRecord::Base
    belongs_to :school
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    if logged_in? #testar se usuário logou
        @jobs=Job.where(school_id: session[:school_id]) #lista vagas
    else
      redirect_to login_path, notice: 'Você precisa estar logado'
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:occupation, :salary, :description, :qualification, :graduation, :vacancies, :workplace, :benefits, :schedule)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :occupation %><br>
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :qualification %><br>
    <%= f.text_area :qualification %>
  </div>
  <div class="field">
    <%= f.label :graduation %><br>
    <%= f.text_field :graduation %>
  </div>
  <div class="field">
    <%= f.label :vacancies %><br>
    <%= f.text_field :vacancies %>
  </div>
  <div class="field">
    <%= f.label :workplace %><br>
    <%= f.text_field :workplace %>
  </div>
  <div class="field">
    <%= f.label :benefits %><br>
    <%= f.text_area :benefits %>
  </div>
  <div class="field">
    <%= f.label :schedule %><br>
    <%= f.text_field :schedule %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Occupation</th>
      <th>Salary</th>
      <th>Description</th>
      <th>Qualification</th>
      <th>Graduation</th>
      <th>Vacancies</th>
      <th>Workplace</th>
      <th>Benefits</th>
      <th>Schedule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.occupation %></td>
        <td><%= job.salary %></td>
        <td><%= job.description %></td>
        <td><%= job.qualification %></td>
        <td><%= job.graduation %></td>
        <td><%= job.vacancies %></td>
        <td><%= job.workplace %></td>
        <td><%= job.benefits %></td>
        <td><%= job.schedule %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Occupation:</strong>
  <%= @job.occupation %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @job.salary %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @job.qualification %>
</p>

<p>
  <strong>Graduation:</strong>
  <%= @job.graduation %>
</p>

<p>
  <strong>Vacancies:</strong>
  <%= @job.vacancies %>
</p>

<p>
  <strong>Workplace:</strong>
  <%= @job.workplace %>
</p>

<p>
  <strong>Benefits:</strong>
  <%= @job.benefits %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @job.schedule %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>